/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Dao.DAO_Aeroporto;
import Model.Table.VooTableModel;
import Model.Value.Voo;
import javax.swing.JOptionPane;
import Controler.Configs;
import Controler.Secure;
import Controler.Validacao;
import Model.Table.AeronavesTableModel;
import Model.Table.ReservasTableModel;
import Model.Value.Aeronaves;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;
/**
 *
 * @author Administrator
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        actualizarTabela();
        
       
        
        this.setLocation(300, 150);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        verAeronaves = new javax.swing.JButton();
        Info = new javax.swing.JLabel();
        vervoos = new javax.swing.JButton();
        verreservas2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setBackground(Configs.color);
        jButton1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButton1.setText("Actualizar voo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(Configs.color);
        jButton2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButton2.setText("Deletar voo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(Configs.color);
        jButton3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButton3.setText("Adicionar voo");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTextField1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                key(evt);
            }
        });

        jButton4.setBackground(Configs.color);
        jButton4.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButton4.setText("Pesquisar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jScrollPane2.setViewportView(jScrollPane1);

        jButton5.setBackground(Configs.color);
        jButton5.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButton5.setText("Reservar Assento");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        verAeronaves.setBackground(Configs.color);
        verAeronaves.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        verAeronaves.setText("Ver Aeronaves");
        verAeronaves.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verAeronavesActionPerformed(evt);
            }
        });

        Info.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Info.setText("INFORMACOES DOS VOOS");

        vervoos.setBackground(Configs.color);
        vervoos.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        vervoos.setText("Ver Voos");
        vervoos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vervoosActionPerformed(evt);
            }
        });

        verreservas2.setBackground(Configs.color);
        verreservas2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        verreservas2.setText("Ver Reservas");
        verreservas2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verreservas2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(169, 169, 169)
                                .addComponent(jButton2)
                                .addGap(1, 1, 1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 780, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(verAeronaves, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(vervoos, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(verreservas2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(Info, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Info))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(vervoos, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(verreservas2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(verAeronaves, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         Trecho t = new Trecho();
         t.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if(temLinhaSelecionada()){
            DAO_Aeroporto dao = new DAO_Aeroporto();
            int x = Integer.parseInt((String) jTable1.getValueAt(jTable1.getSelectedRow(), 0));
            
            Voo v = dao.recuperar(x); 
            ReservaAssento ra = new ReservaAssento(v);
            ra.setVisible(true);
            actualizarTabela();
        }else{
            JOptionPane.showMessageDialog(null, "Erro!Selecione uma linha e Tente Novamente.");

        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(temLinhaSelecionada()){
            Secure.isUpdate = false;
            DAO_Aeroporto dao = new DAO_Aeroporto();
            int x = Integer.parseInt((String) jTable1.getValueAt(jTable1.getSelectedRow(), 0));
            dao.deletar(x);    
            actualizarTabela();
        }else{
            JOptionPane.showMessageDialog(null, "Erro!Selecione uma linha e Tente Novamente.");

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(temLinhaSelecionada()){
            Secure.isUpdate = true;
            DAO_Aeroporto dao = new DAO_Aeroporto();
            int x = Integer.parseInt((String) jTable1.getValueAt(jTable1.getSelectedRow(), 0));
            Voo v = dao.recuperar(x); 
            
            Trecho t = new Trecho(v);
            t.setVisible(true);
            actualizarTabela();
        }else{
            JOptionPane.showMessageDialog(null, "Erro!Selecione uma linha e Tente Novamente.");

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Validacao v=new Validacao();
        if(v.validarInt(jTextField1.getText(), 1, 99999)){
//            TableRowSorter rs = (TableRowSorter) jTable1.getRowSorter();
//            rs.setRowFilter(RowFilter.regexFilter("(?i)" + jTextField1.getText(), 0, 1)); 
        }else{
            actualizarTabela();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void verAeronavesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verAeronavesActionPerformed
         //if(temLinhaSelecionada()){
             
            //int x = Integer.parseInt((String) jTable1.getValueAt(jTable1.getSelectedRow(), 0));
            jTable1.setModel(new AeronavesTableModel());
            AeronavesTableModel ctm = (AeronavesTableModel)  jTable1.getModel();
            
            DAO_Aeroporto daoA = new DAO_Aeroporto();
            ctm.setDados(daoA.listarAeronaves());
            jScrollPane2.setViewportView(jTable1);
            Info.setText("AERONAVES");
//        }else{
//            JOptionPane.showMessageDialog(null, "Erro!Selecione uma linha e Tente Novamente.");
//
//        }
    }//GEN-LAST:event_verAeronavesActionPerformed

    private void vervoosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vervoosActionPerformed
       Info.setText("INFORMACOES DOS VOOS"); actualizarTabela();
    }//GEN-LAST:event_vervoosActionPerformed

    private void verreservas2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verreservas2ActionPerformed
        if(Info.getText().equalsIgnoreCase("INFORMACOES DOS VOOS")){
                
                if(temLinhaSelecionada()){
           
                
            int x = Integer.parseInt((String) jTable1.getValueAt(jTable1.getSelectedRow(), 0));
            jTable1.setModel(new ReservasTableModel());
            ReservasTableModel ctm = (ReservasTableModel)  jTable1.getModel();
            
            DAO_Aeroporto daoA = new DAO_Aeroporto();
            ctm.setDados(daoA.listarReservas(x));
            jScrollPane2.setViewportView(jTable1);
            Info.setText("RESERVAS DO VOO :"+x);
            }else{
                JOptionPane.showMessageDialog(null, "Erro!Selecione uma linha e Tente Novamente.");

            }
        }else{
            Info.setText("INFORMACOES DOS VOOS"); actualizarTabela();
        }
        
    }//GEN-LAST:event_verreservas2ActionPerformed

    private void key(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_key
                      // TODO add your handling code here:
    }//GEN-LAST:event_key

    private boolean temLinhaSelecionada() {
        boolean x =false;
        int c=0;
         for (int i = 0; i < jTable1.getRowCount(); i++) {
           if(jTable1.isRowSelected(i)){
               c++;
           }
        }
        if (c==1) {
            x=true;
        }
        return x;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Info;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton verAeronaves;
    private javax.swing.JButton verreservas2;
    private javax.swing.JButton vervoos;
    // End of variables declaration//GEN-END:variables

    private void actualizarTabela() {
        jTable1.setModel(new VooTableModel());
        VooTableModel ctm = (VooTableModel)  jTable1.getModel();
        DAO_Aeroporto daoA = new DAO_Aeroporto();
        ctm.setDados(daoA.listarTodos());
        jScrollPane2.setViewportView(jTable1);
    }
}
