/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controler.Configs;
import Controler.Secure;
import Controler.Validacao;
import Model.Dao.DAO_Aeroporto;
import Model.Value.Voo;
import java.awt.Color;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import javax.swing.border.LineBorder;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Administrator
 */
public class Trecho extends javax.swing.JFrame {
    private boolean update = false;
    /**
     * Creates new form Trecho
     */
    public Trecho() {
        initComponents();
        Assentos.setModel(new SpinnerNumberModel(1,1,99999,1));
        formatar();
        this.setLocation(300, 150);
    }
    public Trecho(Voo v1) {
        initComponents();
        update = true;
        
        NrVoo.setText(v1.getNrVoo());
        NrTrecho.setText(v1.getNrTrecho());
        Data.setText(v1.getData());
        
        int n = Integer.parseInt(v1.getAssentosDis());
        Assentos.setModel(new SpinnerNumberModel(1,1,99999,1));
        Assentos.setValue(n);
        
        CodAeronave.setText(v1.getCodAeronave());
        HorarioPartida.setText(v1.getPartida());
        HorarioChegada.setText(v1.getChegada());
        CodPartida.setText(v1.getAeroPartida()); 
        CodChegada.setText(v1.getAeroChegada());
        formatar();
       
        this.setLocation(300, 150);
    }
        
    public void formatar(){
        try {
            
            MaskFormatter mask = new MaskFormatter("##/##/####");
            mask.install(Data);
//            if(val.validarInt(Data.getText().substring(0, 2),1,12) ){
//                Data.setBorder(new LineBorder(Color.GREEN, 5)); 
//            }else{
//                Data.setBorder(new LineBorder(Color.RED, 5)); erro+="\n7 - Data Invalida";
//            }
        } catch (ParseException ex) {
            erro +="A data deve ser ##/##/####";
            Data.setBorder(new LineBorder(Color.RED, 5));
            //Logger.getLogger(Trecho.class.getName()).log(Level.SEVERE, null, ex);
        }
        
         try {
            MaskFormatter mask = new MaskFormatter("##:##");
            mask.install(HorarioChegada);
        } catch (ParseException ex) {
            erro +="A Hora deve ser ##:##";
            HorarioChegada.setBorder(new LineBorder(Color.RED, 5));
        }
        try {
            MaskFormatter mask = new MaskFormatter("##:##");
            mask.install(HorarioPartida);
        } catch (ParseException ex) {
            erro +="A Hora deve ser ##:##";
            HorarioPartida.setBorder(new LineBorder(Color.RED, 5));
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        Data = new javax.swing.JFormattedTextField();
        CodAeronave = new javax.swing.JTextField();
        HorarioPartida = new javax.swing.JFormattedTextField();
        HorarioChegada = new javax.swing.JFormattedTextField();
        NrTrecho = new javax.swing.JTextField();
        NrVoo = new javax.swing.JTextField();
        Assentos = new javax.swing.JSpinner();
        CodPartida = new javax.swing.JTextField();
        CodChegada = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setText("Nr. Voo");

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel2.setText("Nr. Trecho");

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel3.setText("Data");

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel4.setText("Assentos");

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel6.setText("Cod Aeroporto partida");

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel7.setText("Cod Aeroporto Chegada");

        jLabel14.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel14.setText("Cod Aeronave");

        jLabel17.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel17.setText("Horario de partida");

        jLabel18.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel18.setText("Horario de chegada");

        jLabel19.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel19.setText("Informacoes do Voo");

        jButton1.setBackground(Configs.color);
        jButton1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(Configs.color);
        jButton2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButton2.setText("Proximo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Data)
                            .addComponent(NrTrecho)
                            .addComponent(NrVoo)
                            .addComponent(Assentos, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addGap(55, 55, 55))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel18)
                                            .addComponent(jLabel17))
                                        .addGap(10, 10, 10)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(HorarioPartida)
                                    .addComponent(HorarioChegada)
                                    .addComponent(CodAeronave, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)))))
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CodPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CodChegada, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(NrVoo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(NrTrecho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(CodAeronave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(HorarioPartida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(Data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HorarioChegada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Assentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(CodPartida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(CodChegada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
        validar();
        if(erro.equals("")){
            Voo voo = new Voo();
            Secure.NrVoo = NrVoo.getText();
            Secure.NrTrecho = NrTrecho.getText();
            Secure.CodAeronave = CodAeronave.getText();
            voo.setNrVoo(NrVoo.getText());
            voo.setNrTrecho(NrTrecho.getText());
            voo.setData(Data.getText());
            voo.setAssentosDis(Assentos.getValue()+"");
            voo.setCodAeronave(CodAeronave.getText());
            voo.setPartida(HorarioPartida.getText());
            voo.setChegada(HorarioChegada.getText());
            voo.setAeroPartida(CodPartida.getText()); 
            voo.setAeroChegada(CodChegada.getText());

            DAO_Aeroporto dao = new DAO_Aeroporto();

            if(update){
                dao.actualizar(voo);
            }else{
                dao.gravarTrecho(voo);
            }

            Tarifa t = new Tarifa(voo);
            t.setVisible(true);
            super.setVisible(false);
            }else{
                    JOptionPane.showMessageDialog(null, erro);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        super.setVisible(false); 
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

  private void validar() {
        erro ="";
        if(val.validarInt(NrVoo.getText(),1,9999999)){
            NrVoo.setBorder(new LineBorder(Color.GREEN, 5)); 
        }else{
            NrVoo.setBorder(new LineBorder(Color.RED, 5)); erro+="\n1 - Nr Voo Invalido";
        }
        if(val.validarInt(NrTrecho.getText(),1,9999999)){
            NrTrecho.setBorder(new LineBorder(Color.GREEN, 5)); 
        }else{
            NrTrecho.setBorder(new LineBorder(Color.RED, 5)); erro+="\n2 - Nr Treco Invalido";
        }
        if(val.validarInt(CodChegada.getText(),1,9999999)){
            CodChegada.setBorder(new LineBorder(Color.GREEN, 5)); 
        }else{
            CodChegada.setBorder(new LineBorder(Color.RED, 5)); erro+="\n3 - Cod Aeroporto de Chegada Invalido";
        }
        if(val.validarInt(CodPartida.getText(),1,9999999)){
            CodPartida.setBorder(new LineBorder(Color.GREEN, 5)); 
        }else{
            CodPartida.setBorder(new LineBorder(Color.RED, 5)); erro+="\n4 - Cod Aeroporto de Partida Invalido";
        }
        if(val.validarInt(CodAeronave.getText(),1,9999999)){
            CodAeronave.setBorder(new LineBorder(Color.GREEN, 5)); 
        }else{
            CodAeronave.setBorder(new LineBorder(Color.RED, 5)); erro+="\n5 - Cod Aeronave Invalido";
        }
       
        
    }
    private Validacao val = new Validacao();
    private String  erro ="";
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner Assentos;
    private javax.swing.JTextField CodAeronave;
    private javax.swing.JTextField CodChegada;
    private javax.swing.JTextField CodPartida;
    private javax.swing.JFormattedTextField Data;
    private javax.swing.JFormattedTextField HorarioChegada;
    private javax.swing.JFormattedTextField HorarioPartida;
    private javax.swing.JTextField NrTrecho;
    private javax.swing.JTextField NrVoo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
